import {
  Transaction,
  Anomaly,
  ShapValue,
  FeatureWeight,
  Alert,
  ActivityLog,
} from "./types";

export const initialTransactions: Transaction[] = [
  {
    id: "TXN_9420311",
    accountSource: "Main_Checking_01",
    destination: "Ext_Wire_992",
    amount: 12450.0,
    timestamp: "2024-10-21 14:22:10",
    velocityFlag: "NORMAL",
    riskScore: 24.5,
    probability: 0.12,
    category: "Standard Outflow",
    status: "Resolved",
  },
  {
    id: "TXN_9420312",
    accountSource: "Global_X_Savings",
    destination: "Venmo_P2P_88",
    amount: 890.0,
    timestamp: "2024-10-21 14:22:15",
    velocityFlag: "HIGH_RISK",
    riskScore: 98.4,
    probability: 0.94,
    category: "Mule Candidate",
    status: "Active Alert",
  },
  {
    id: "TXN_9420313",
    accountSource: "Corporate_Float_A",
    destination: "Internal_Trf",
    amount: 155000.0,
    timestamp: "2024-10-21 14:22:18",
    velocityFlag: "NORMAL",
    riskScore: 12.0,
    probability: 0.02,
    category: "Liquidity Moving",
    status: "Resolved",
  },
  {
    id: "TXN_9420314",
    accountSource: "ACC-0482-11",
    destination: "Crypto_Escrow_7",
    amount: 45000.0,
    timestamp: "2024-10-21 14:18:03",
    velocityFlag: "HIGH_RISK",
    riskScore: 94.0,
    probability: 0.94,
    category: "High Velocity Mule",
    status: "Active Alert",
  },
  {
    id: "TXN_9420315",
    accountSource: "ACC-9920-54",
    destination: "Shell_Holding_Group",
    amount: 22100.0,
    timestamp: "2024-10-21 14:05:12",
    velocityFlag: "SUSPICIOUS",
    riskScore: 68.2,
    probability: 0.68,
    category: "Layering Pattern",
    status: "Under Review",
  },
  {
    id: "TXN_9420316",
    accountSource: "ACC-7712-30",
    destination: "Smurf_Cash_Out",
    amount: 9800.0,
    timestamp: "2024-10-21 13:21:44",
    velocityFlag: "SUSPICIOUS",
    riskScore: 42.0,
    probability: 0.42,
    category: "Smurfing Attempt",
    status: "Resolved",
  },
  {
    id: "TXN_9420317",
    accountSource: "ACC-0012-99",
    destination: "Offshore_Trust_A",
    amount: 89000.0,
    timestamp: "2024-10-21 11:15:30",
    velocityFlag: "HIGH_RISK",
    riskScore: 89.9,
    probability: 0.82,
    category: "Shell Org Signal",
    status: "Active Alert",
  },
  {
    id: "TXN_9420318",
    accountSource: "Main_Savings_99",
    destination: "Internal_Transfer",
    amount: 1200.0,
    timestamp: "2024-10-21 10:45:00",
    velocityFlag: "NORMAL",
    riskScore: 5.4,
    probability: 0.01,
    category: "Standard Transfer",
    status: "Resolved",
  },
];

export const mockAnomalies: Anomaly[] = [
  {
    id: "ANM-001",
    title: "Rapid Fund Redistribution",
    description:
      "Account ending in *4492 received $45k via 12 deposits, emptied in 4 mins.",
    timeAgo: "2m ago",
    riskType: "error",
    riskLevel: "High Probability",
    accountEnding: "*4492",
  },
  {
    id: "ANM-002",
    title: "New Device Linking",
    description:
      "Foreign IP address detected (192.168.x.x) for account *1102.",
    timeAgo: "14m ago",
    riskType: "warning",
    riskLevel: "Medium Risk",
    accountEnding: "*1102",
  },
  {
    id: "ANM-003",
    title: "Layering Activity Detected",
    description:
      "Cluster of 5 accounts displaying smurfing patterns in NYC region.",
    timeAgo: "31m ago",
    riskType: "primary",
    riskLevel: "High Velocity",
    accountEnding: "*9901",
  },
];

export const mockShapValues: ShapValue[] = [
  {
    feature: "Velocity_30d",
    impactValue: 0.42,
    impactType: "positive",
    displayValue: "+0.42",
  },
  {
    feature: "Avg_Txn_Amount",
    impactValue: -0.28,
    impactType: "negative",
    displayValue: "-0.28",
  },
  {
    feature: "IP_Risk_Score",
    impactValue: 0.51,
    impactType: "positive",
    displayValue: "+0.51",
  },
  {
    feature: "Device_History",
    impactValue: 0.12,
    impactType: "positive",
    displayValue: "+0.12",
  },
  {
    feature: "Cross_Border_Freq",
    impactValue: 0.38,
    impactType: "positive",
    displayValue: "+0.38",
  },
];

export const mockFeatureWeights: FeatureWeight[] = [
  { feature: "Transaction Velocity", weightPercent: 82, importance: "high" },
  { feature: "Identity Mismatch", weightPercent: 64, importance: "high" },
  {
    feature: "Dormant Account Activation",
    weightPercent: 45,
    importance: "medium",
  },
  {
    feature: "High-Risk Jurisdiction",
    weightPercent: 31,
    importance: "low",
  },
];

export const initialAlerts: Alert[] = [
  {
    id: "#AL-9921",
    accountId: "ACC-0482-11",
    category: "High Velocity Mule",
    confidence: 94,
    detectedTime: "2m ago",
    status: "Active Alert",
  },
  {
    id: "#AL-9844",
    accountId: "ACC-9920-54",
    category: "Layering Pattern",
    confidence: 68,
    detectedTime: "15m ago",
    status: "Under Review",
  },
  {
    id: "#AL-9812",
    accountId: "ACC-7712-30",
    category: "Smurfing Attempt",
    confidence: 42,
    detectedTime: "1h ago",
    status: "Resolved",
  },
  {
    id: "#AL-9755",
    accountId: "ACC-0012-99",
    category: "Shell Org Signal",
    confidence: 82,
    detectedTime: "3h ago",
    status: "Active Alert",
  },
  {
    id: "#AL-9610",
    accountId: "ACC-1049-74",
    category: "Sanction List Match",
    confidence: 99,
    detectedTime: "5h ago",
    status: "Active Alert",
  },
  {
    id: "#AL-9423",
    accountId: "ACC-5521-LM",
    category: "Rapid Money Flow",
    confidence: 88,
    detectedTime: "1d ago",
    status: "Active Alert",
  },
  {
    id: "#AL-9241",
    accountId: "ACC-0052-12",
    category: "Micro-Structuring",
    confidence: 51,
    detectedTime: "2d ago",
    status: "Resolved",
  },
];

export const mockActivityLogs: ActivityLog[] = [
  {
    id: "LOG-01",
    fileName: "Q3_2024_Mule_Audit.pdf",
    exportedBy: "Sarah Chen",
    timeAgo: "2h ago",
    type: "pdf",
  },
  {
    id: "LOG-02",
    fileName: "Risk_Summary_Sep_24.xlsx",
    exportedBy: "System (Auto)",
    timeAgo: "1d ago",
    type: "excel",
  },
  {
    id: "LOG-03",
    fileName: "High_Alert_Audit_Trail.pdf",
    exportedBy: "Compliance Officer",
    timeAgo: "3d ago",
    type: "warning",
  },
];
